# Generated by Django 3.2.4 on 2021-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cat_cattoys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cattoys',
            field=models.ManyToManyField(to='main_app.CatToy', verbose_name='list of toys'),
        ),
    ]
